// Creates .env.local with generated secrets on first run so `npm run dev`
// works with zero configuration. Never overwrites existing values.
import { randomBytes } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const envPath = path.join(process.cwd(), ".env.local");
const existing = fs.existsSync(envPath) ? fs.readFileSync(envPath, "utf8") : "";

const has = (key) => new RegExp(`^\\s*${key}\\s*=`, "m").test(existing);

const additions = [];
if (!has("BETTER_AUTH_SECRET")) {
  additions.push(`BETTER_AUTH_SECRET=${randomBytes(32).toString("base64")}`);
}
if (!has("ENCRYPTION_KEY")) {
  additions.push(`ENCRYPTION_KEY=${randomBytes(32).toString("hex")}`);
}
if (!has("BETTER_AUTH_URL")) {
  additions.push(`BETTER_AUTH_URL=http://localhost:3000`);
}

if (additions.length) {
  const header = existing.trim().length
    ? "\n# --- added by scripts/ensure-env.mjs ---\n"
    : "# Generated by scripts/ensure-env.mjs. See .env.example for all options.\n";
  fs.writeFileSync(envPath, existing + header + additions.join("\n") + "\n");
  console.log(`[howitsgoing] wrote ${additions.length} secret(s) to .env.local`);
}
